### ISSUE TITLE
Session cookie not preserved after redirect + post_data not erased in session

### ISSUE THREAD

**Issue by mbourquin** [samsonasik/expressive3-example-auth-with-prg#1]
Hi Samsonasik,

We already exchanged some messages about it on your blog some months ago.
Because of the redirect 302, it seems that browser lost the session cookie and recreate a new session (i read some posts on internet about that behavior). It is the reason why i have 2 session all the time created in my server for one form post (login) when i use PRG.

My problem is that my credentials (username / password) still in the initial session in the post_data variable and are not erased before redirecting. For my part is it a potential security risk to have a raw password in session (a orphan session).

$session->unset('post_data') seems to do not erase the content, i have to add unset($_SESSION['post_data']). 

Can you please check it? If you also have that behavior.

In your PrgMiddleware:

    if ($session->has('post_data')) {
        $post = $session->get('post_data');
    
        $session->unset('post_data'); <-- SEEMS TO DO NOT ERASE THE CONTENT
        unset($_SESSION['post_data']);  <-- ADDED THIS TO ERASE THE CONTENT

        $request = $request->withMethod('POST');
        $request = $request->withParsedBody($post);
    }

Thanks!

You already upgrade to Mezzio but is not a problem ;)

**Comment by samsonasik** [comment]
@mbourquin I just re-check and it seems the "old" session not actually removed, while it is no longer used. Hopefully I can check if there will be solution for it instead of manually...

**Comment by samsonasik** [comment]
@mbourquin I just updated session components packages, then check session name after update to `Mezzio` namespace, and got the session name not yet updated in `LoginPageHandler` class at https://github.com/samsonasik/expressive3-example-auth-with-prg/commit/83a649fe8800b68de09a2266f2bd545b8036cb6a , I updated it and it seems fixes the issue.

If you use clone, could you re-pull and retry composer install ? :

```bash
git pull origin master
composer install
```

and verify if that fixes the issue ? Thank you.

**Comment by mbourquin** [comment]
@samsonasik Thanks but i'm still using Expressive, i will change to Mezzio next month after official launch ;) I just checked your new commits but i'm already use the last session-* authentication, ...   So i'm still must use unset($_SESSION['post_data']) in the middleware. But it's works good like workaround.

I will try to test your version in the next days..

**Comment by samsonasik** [comment]
@mbourquin I just re-checked again, and indeed, you're correct, the `unset($_SESSION['post_data']);` is the workaround solution for now. I'm thinking if there can be a specific `Response` to apply the session unset.

**Comment by samsonasik** [comment]
Hi @@mbourquin , it fixed now. The solution is place the `App\Middleware\PrgMiddleware::class` registration in the end of login route, and then, place as well in the begin of target route, eg: home route. Please check this change https://github.com/samsonasik/expressive3-example-auth-with-prg/commit/ccb0decdb24088eb011423f394d24d1b90554d73

Thank you for the bug report.

**Comment by mbourquin** [comment]
@samsonasik You're welcome! and thanks for the solution! I will update my code tomorrow.
